### ISSUE TITLE
Use stream instead of parallelStream internally

### ISSUE THREAD

**Issue by mbyrne00** [n15g/spring-boot-gae#2]
Most queries are designed to work with manageable sized data sets (200 or less) and as such the benefits of `parallelStream` are questionable ... probably degrading in performance. Threading can also complicate things (threadocal, etc) so it's best to avoid trying to prematurely optimise with parallel processing. Many apps are deployed on low-spec CPUs as well (instances scaled horizontally).

There's a bit of chatter about it. For example: 
* https://blog.oio.de/2016/01/22/parallel-stream-processing-in-java-8-performance-of-sequential-vs-parallel-stream-processing/
* https://zeroturnaround.com/rebellabs/java-parallel-streams-are-bad-for-your-health/

I think if we are going to have a default stance, let's stick with the standard `stream`.

**Comment by n15g** [comment]
Yeah, don't know what I was thinking there... Thanks Matt.

As much as I want to believe the 'it just works' argument of Java 8's parallelism, I'm dubious of whether it might cuase issues anyway. AppEngine doesn't play nicely with threads in some instances (particularly on the old custom JDK 7 flavor, may be much better in the containerized version, but haven't checked), and Objectify definitely doesn't like them.

I'll go through and switch out all the calls to parallelStream to stream.

**Comment by kuhnza** [comment]
This is resolved by PR #3.

**Comment by n15g** [comment]
Fixed in 1.1.0-beta-1, awaiting release.
