### ISSUE TITLE
Update version with "beta-1" suffix and add note to top of readme to say API may have breaking changes

### ISSUE THREAD

**Issue by mbyrne00** [n15g/spring-boot-gae#4]
Just so we don't limit ourselves in this early phase it would be good to notify people that there may be breaking changes coming.

**Comment by n15g** [comment]
I'll make the release 1.1 as well, a minor version number change is a good indicator of breaking changes.

1.1.0-beta-1?

**Comment by n15g** [comment]
Fixed in 1.1.0-beta-1, awaiting release.
