### ISSUE TITLE
Bundle test jar

### ISSUE THREAD

**Issue by kuhnza** [n15g/spring-boot-gae#5]
It would be really helpful if we bundled a test jar that contained the ObjectifyTest base class, SetupAppengine rule etc.

Have copied them out of src/test for now and modified them for my project but ideally these would just be test scoped dependency.

**Comment by n15g** [comment]
Not a bad idea, and should be fairly trivial to set up as part of the release config.

I'll take a crack at it now.

**Comment by n15g** [comment]
Compiled tests and sources will be deployed from version `1.1.0-beta-3` onward. This is now available in central.

You can add them with:
```testCompile 'com.github.n15g:spring-boot-gae:1.1.0-beta-3:tests'```
or
```
<dependency>
            <groupId>com.github.n15g</groupId>
            <artifactId>spring-boot-gae</artifactId>
            <version>1.1.0-beta-3</version>
            <type>test-jar</type>
        </dependency>
```

**Comment by kuhnza** [comment]
Thanks for the quick turnaround! 

Unless I'm missing something, I suspect we're going to have to rejig some of those classes? In particular I'm thinking of ObjectifyTest which doesn't work out of the box as it's hard coded to use the ObjectifyTestConfiguration which only registers the entities used in the libraries test cases.

My tests were also complaining about the ObjectifyProxy which is bundled in. I ended up removing it just so I could move on.

**Comment by n15g** [comment]
Yeah, some rejigging is probably necessary. They weren't really designed to be used for tests outside the project. There's a fair amount of Spring context configuration specific to the tests for a start.

It's probably better to make those classes internal and create some generified ones to extend for testing.  They're there at least now if anyone wants to make use of them, and the source is also, so they can be copied if needed.

I'll raise a new issue to add some better base test classes.

**Comment by kuhnza** [comment]
That's a good idea. If I get a chance I'll see what I can bring across from the project I'm working on.
